name: Docker Registry Cleanup

# https://docs.github.com/en/actions/reference/events-that-trigger-workflows#registry_package
# Run cleanup job if a new package was published or updated
on:
  registry_package:

jobs:
  fail_purging_semantic:
    runs-on: ubuntu-latest
    steps:
      - name: clean packages
        uses: MobileheadHolding/github-action-purge-packages@v2.0.1
        with:
          owner: ${{ github.repository_owner}}
          repo: ${{ github.event.repository.name }}
          version-regex: 'sha*'
          days-old: 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
