name: Docker Registry Cleanup

# https://docs.github.com/en/actions/reference/events-that-trigger-workflows#registry_package
# Run cleanup job if a new package was published or updated
on:
  registry_package:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  fail_purging_semantic:
    runs-on: ubuntu-latest
    steps:
      - name: clean packages
        uses: MobileheadHolding/github-action-purge-packages@v2.0.1
        with:
          owner: mpfeil
          repo: ghcr
          version-regex: 'sha*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
