name: Check Watterott senseBox MCU Core for updates

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # Check every day

jobs:
  check-for-updates:
    name: Check for new commits
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'watterott/senseBox-MCU'
          ref: 'master'

      - run: |
          echo "Checking git log"
          git remote show origin
          git log --after="6 months ago" > commits.txt
          wc -l <commits.txt

      - uses: actions/checkout@v2
      - run: |
          echo "Now using this repo"
          git remote show origin
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}